import { IconCircleArrowDown, IconCircleArrowUp, IconBrandGithub  } from '@tabler/icons-react';
import { Carousel } from '@mantine/carousel';
import { Button, Card, Group, Image, Text, Collapse, Center  } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import classes from './Projects.module.css';

const images = [
  'projects/moneyMap/homePage1.png',
  'projects/moneyMap/homePage2.png',
  'projects/moneyMap/transactionLogs.png',
  'projects/moneyMap/addTransaction.png',
  'projects/moneyMap/budgetTracker.png',
  'projects/moneyMap/goals.png',
  'projects/moneyMap/saveGoal.png',
  'projects/moneyMap/AIchat.png',
  'projects/moneyMap/AIchat2.png',
];

export function Projects() {
    const [opened, { toggle }] = useDisclosure(false);

    const slides = images.map((image) => (
        <Carousel.Slide key={image}>
        <Image src={image} height={390} />
        </Carousel.Slide>
    ));

    return (
        <Card radius="md" withBorder padding="xl" mt="xl" className={classes.card}>
            <Card.Section>
                <Carousel
                slideSize="80%"
                controlSize={45}
                withControls
                withIndicators
                slideGap="lg"
                emblaOptions={{ loop: true, align: 'center' }}
                classNames={{
                    root: classes.carousel,
                    controls: classes.carouselControls,
                    indicator: classes.carouselIndicator,
                }}
                >
                {slides}
                </Carousel>
            </Card.Section>

            <Group justify="space-between" mt="xl">
                <Text fw={500} fz="lg" style={{  textShadow: '0 4px 12px rgba(147, 51, 234, 0.8)'}}>
                MoneyMap (AI-Powered Budget Assistant)
                </Text>
            </Group>

            <Text fz="md" mt="lg" ta="left">
                <strong>MoneyMap</strong> is a cross-platform, AI-powered budget assistant built with Electron and React,
                offering a native desktop experience with seamless integration of cloud-based AI via the OpenAI API.
                It combines smart financial tracking, real-time chart visualizations, personal goal management,
                and an AI chat assistant — while all user data is stored locally with fast and secure SQLite storage
                to ensure privacy and performance. Designed with the sleek Mantine UI library, the app delivers both
                functionality and aesthetic clarity for managing your personal finances.
            </Text>

            <Center  justify="space-between" mt="xl">
                <Button onClick={toggle} radius="md" mr="10" className={classes.learnMoreBtn}>
                    Learn More
                    {opened ? <IconCircleArrowUp style={{marginLeft: "10"}}/> : <IconCircleArrowDown style={{marginLeft: "10"}}/>}
                </Button>
                 <Button radius="md" className={classes.githubBtn} ml="5" component="a" 
                        href="https://github.com/vyatsenk0/MoneyMap" target="_blank" rel="noopener noreferrer">
                    GitHub
                    <IconBrandGithub style={{marginLeft: "10"}}/>
                </Button>
            </Center >

            <Collapse in={opened} transitionDuration={1000} transitionTimingFunction="linear">
                <Text mt="xl" fw={500}>💡 Key Features:</Text>
                <ul style={{ paddingLeft: 20,  textAlign: 'left'}}>
                    <li>
                    <strong>AI Home Dashboard:</strong> Real-time financial summaries, insights, and personalized recommendations generated by an AI model through local data analysis
                    </li>
                    <li>
                    <strong>Transaction Log:</strong> Add, edit, and delete income or expense entries in a clean, intuitive interface.
                    </li>
                    <li>
                    <strong>Track Budget:</strong> Visualize income vs. expenses with bar, pie, and line charts that update as you go.
                    </li>
                    <li>
                    <strong>Financial Goals Dashboard:</strong> Set savings goals, track progress, manage recurring contributions, and view goal history.
                    </li>
                    <li>
                    <strong>AI Chat Assistant:</strong> Ask questions about your finances, uncover trends, receive suggestions, and store conversations privately.
                    </li>
                </ul>

                <Text mt="xl" fw={500}>🛠 Tech Stack:</Text>
                <ul style={{ paddingLeft: 20, textAlign: 'left' }}>
                    <li>
                        <strong>Electron:</strong> Native desktop app framework (Windows/macOS/Linux)
                    </li>
                    <li>
                        <strong>React:</strong> Frontend library for dynamic user interfaces
                    </li>
                    <li>
                        <strong>Mantine:</strong> UI component library for clean, responsive design
                    </li>
                    <li>
                        <strong>@mantine/charts:</strong> Built-in chart components (PieChart, BarChart, LineChart) for real-time financial visualization
                    </li>
                    <li>
                        <strong>SQLite3:</strong> Lightweight embedded database for fast, secure local storage
                    </li>
                    <li>
                        <strong>Sequelize:</strong> ORM for managing local SQLite database interactions
                    </li>
                    <li>
                        <strong>OpenAI API:</strong> Cloud-based AI assistant for smart financial insights and conversational interaction
                    </li>
                </ul>

            </Collapse>
        </Card>
    );
}