import { IconStarFilled } from '@tabler/icons-react';
import { Carousel } from '@mantine/carousel';
import { Button, Card, Group, Image, Text, Collapse } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import classes from './Projects.module.css';

const images = [
  'projects/moneyMap/homePage1.png',
  'projects/moneyMap/homePage2.png',
  'projects/moneyMap/transactionLogs.png',
  'projects/moneyMap/addTransaction.png',
  'projects/moneyMap/budgetTracker.png',
  'projects/moneyMap/goals.png',
  'projects/moneyMap/saveGoal.png',
  'projects/moneyMap/AIchat.png',
  'projects/moneyMap/AIchat2.png',
];

export function Projects() {
    const [opened, { toggle }] = useDisclosure(false);

    const slides = images.map((image) => (
        <Carousel.Slide key={image}>
        <Image src={image} height={390} />
        </Carousel.Slide>
    ));

    return (
        <Card radius="md" withBorder padding="xl" mt="xl" className={classes.card}>
            <Card.Section>
                <Carousel
                slideSize="80%"
                controlSize={45}
                withControls
                withIndicators
                slideGap="lg"
                emblaOptions={{ loop: true, align: 'center' }}
                classNames={{
                    root: classes.carousel,
                    controls: classes.carouselControls,
                    indicator: classes.carouselIndicator,
                }}
                >
                {slides}
                </Carousel>
            </Card.Section>

            <Group justify="space-between" mt="lg">
                <Text fw={500} fz="lg">
                AI-Powered Budget Assistant
                </Text>
            </Group>

            <Text fz="sm" c="dimmed" mt="sm" ta="left">
                Cross-platform AI-powered budget assistant built with Electron and React. Includes smart financial insights, goal tracking, real-time charts, and a local AI chatbot — all stored securely with SQLite.
            </Text>

            <Group justify="space-between" mt="md">
                <Button onClick={toggle} radius="md"
                        style={{background: 'linear-gradient(to right, #2172f4, #5b43d6, #9333ea)',
                        color: 'white',
                        opacity: 0.8
                }}>
                    Learn More
                </Button>
            </Group>

            <Collapse in={opened} transitionDuration={1000} transitionTimingFunction="linear">
                <Text mt="xl" ta="left">
                    <strong>A cross-platform native desktop application</strong> built with Electron and React, featuring both frontend and backend logic. Designed with the Mantine UI component library for a clean, modern interface. Data is stored locally using SQLite, ensuring user privacy and fast access.
                </Text>
                <Text mt="xl" fw={500}>💡 Key Features:</Text>
                <ul style={{ paddingLeft: 20,  textAlign: 'left'}}>
                    <li>
                    <strong>AI Home Dashboard:</strong> Real-time financial summaries, insights, and personalized recommendations generated by an AI model analyzing local data.
                    </li>
                    <li>
                    <strong>Transaction Log:</strong> Add, edit, or delete income and expenses in an intuitive interface.
                    </li>
                    <li>
                    <strong>Track Budget:</strong> Visualize income vs. expenses and financial health using bar, pie, and line charts.
                    </li>
                    <li>
                    <strong>Financial Goals Dashboard:</strong> Set target amounts, track progress, configure recurring contributions, and manage goal history.
                    </li>
                    <li>
                    <strong>AI Chat Assistant:</strong> Analyze your financial data, explain patterns, suggest optimizations, and store chats in searchable history.
                    </li>
                </ul>
            </Collapse>
        </Card>
    );
}